import {test, expect} from '@playwright/test';

const FIXTURE_NAMES = [
  'text',
  'text-bound',
  'text-sizes',
  'text-weights',
  'text-as',
  'text-whitespace',
  'button-fn',
  'button-event',
  'button-variants',
  'button-sizes',
  'button-aligncontent',
  'button-disabled',
  'button-inactive',
  'button-loading',
  'button-block',
  'button-labelwrap',
  'button-count',
  'button-icon',
  'button-leading-visual',
  'button-trailing-visual',
  'button-trailing-action',
  'icon-names',
  'icon-sizes',
  'icon-fills',
  'link',
  'link-bound',
  'link-muted',
  'link-inline',
  'heading',
  'heading-bound',
  'heading-variants',
  'branchname',
  'branchname-bound',
  'branchname-as',
  'relative-time',
  'relative-time-bound',
  'relative-time-formats',
  'relative-time-format-styles',
  'relative-time-tenses',
  'relative-time-precision',
  'relative-time-threshold',
  'relative-time-prefix',
  'relative-time-datetime-parts',
  'label',
  'label-bound',
  'label-variants',
  'label-sizes',
  'statelabel',
  'statelabel-bound',
  'statelabel-status',
  'statelabel-size',
  'counterlabel',
  'counterlabel-bound',
  'counterlabel-variants',
  'spinner',
  'spinner-sizes',
  'token',
  'token-bound',
  'token-leadingvisual',
  'token-sizes',
  'token-selected',
  'token-disabled',
  'token-remove-fn',
  'token-remove-event',
  'token-hideremovebutton',
  'issuelabeltoken',
  'issuelabeltoken-bound',
  'issuelabeltoken-fillcolor',
  'issuelabeltoken-sizes',
  'issuelabeltoken-selected',
  'issuelabeltoken-disabled',
  'issuelabeltoken-remove-fn',
  'issuelabeltoken-remove-event',
  'issuelabeltoken-hideremovebutton',
];

for (const name of FIXTURE_NAMES) {
  test(`baseline: ${name}`, async ({page}) => {
    await page.goto(`/?fixture=${name}`);
    const view = page.getByTestId('fixture-view');
    await expect(view).toBeVisible();
    await expect(view).toHaveScreenshot(`${name}.png`);
  });
}
